#!/usr/bin/env bash
#
# render-setup.sh -- generate an exe.dev `--setup-script` that reproduces keel
# on the STOCK exeuntu image at boot time, instead of pulling the custom
# ghcr.io/missionfocus/keel image.
#
# Why this exists: ghcr.io/boldsoftware/exeuntu is exe.dev's own default image,
# and is presumably kept warm across the fleet -- a custom derivative like keel
# is not, even though most of its bytes are identical. Measured against the
# actual published manifests: keel's own genuinely-new content (apt packages,
# starship/atuin/gum/jj/chezmoi/borg, dotfiles, keel's own scripts) is only
# ~114 MiB; the other ~1.5 GiB is byte-identical exeuntu base layers (same
# digests, since `FROM exeuntu:latest` just references them verbatim). If
# exe.dev pulls reused cached layers by content digest, that ~1.5 GiB should
# cost little either way -- but it doesn't seem to for a non-default image, so
# `just new` pays a cold multi-GB pull essentially every time regardless.
#
# This script reads files/* and the pinned ARG versions out of the
# Containerfile, so THAT remains the single source of truth -- nothing here is
# hand-duplicated. Run it and pipe the output straight into `new`:
#
#   just render-setup | ssh exe.dev new --name mybox \
#       --image=ghcr.io/boldsoftware/exeuntu:latest \
#       --tag dev --setup-script /dev/stdin
#
# or just `just new-fast mybox dev`.
#
# This does NOT replace the Containerfile/CI pipeline -- it is an alternative
# launch path with a real trade-off (see the 10 KiB note below), not a
# replacement. The README explains both.
#
# --- the 10 KiB ceiling ------------------------------------------------------
# exe.dev caps --setup-script at 10 KiB total. Two things had to give to fit:
#
# 1. DEV-ONLY. The full files/* set (borg, keel-backup, its systemd units, the
#    /etc/keel/* config placeholders) alone base64-embeds to well over the
#    limit. Backup is already a deliberate, less-common promotion (see
#    `just enable-backup`), not the common "give me a box" case this
#    optimizes for -- so a VM that needs `backup` should still be built with
#    `just new` (the full custom image). If this VM is later tagged `backup`
#    anyway, keel-profile's `systemctl enable --now keel-backup.timer` fails
#    loudly (unit not found) rather than silently no-op'ing, consistent with
#    the existing fail-loudly design.
# 2. Comments are stripped from the embedded copies of files/* (see
#    strip_comments below) and this script's own prose is kept to one-liners.
#    The reasoning lives here, in render-setup.sh, and in files/* themselves
#    -- not duplicated a third time into a script nobody reads interactively,
#    since exe-setup.service runs it unattended and deletes it on success.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FILES="$HERE/files"

# Pull the pinned tool versions out of the Containerfile so they can't drift
# from the image build. BORG_VERSION deliberately not read -- borg is
# backup-only, out of scope for this dev-only render.
version() {
    grep -m1 "^ARG $1=" "$HERE/Containerfile" | cut -d= -f2
}
STARSHIP_VERSION="$(version STARSHIP_VERSION)"
ATUIN_VERSION="$(version ATUIN_VERSION)"
GUM_VERSION="$(version GUM_VERSION)"
JJ_VERSION="$(version JJ_VERSION)"
CHEZMOI_VERSION="$(version CHEZMOI_VERSION)"
for v in STARSHIP_VERSION ATUIN_VERSION GUM_VERSION JJ_VERSION CHEZMOI_VERSION; do
    [ -n "${!v}" ] || { echo "render-setup: could not read $v from Containerfile" >&2; exit 1; }
done

# Drop comment-only and blank lines (keeping a leading shebang) to buy back
# space under the 10 KiB cap -- see the note at the top of this file. Source
# stays fully commented in files/*; this is a generated, unattended artifact.
strip_comments() {
    awk 'NR==1 && /^#!/ { print; next } /^[[:space:]]*#/ { next } /^[[:space:]]*$/ { next } { print }' "$1"
}

# Embed a small text file byte-for-byte via base64, so there is no heredoc
# quoting/collision risk with the shell scripts and systemd units being
# embedded. `install` args: local file, remote path, mode.
embed() {
    local src="$1" dest="$2" mode="$3"
    printf 'base64 -d <<'"'"'B64EOF'"'"' | sudo tee %q >/dev/null\n' "$dest"
    strip_comments "$FILES/$src" | base64
    printf 'B64EOF\nsudo chmod %s %q\n\n' "$mode" "$dest"
}

cat <<SCRIPT
#!/usr/bin/env bash
# keel setup-script, DEV-ONLY -- generated by render-setup.sh. Do not
# hand-edit; regenerate with \`just render-setup\`. Runs once at first boot as
# exedev, After=network.target only, so network calls below carry their own
# retry rather than trusting boot ordering.
set -euxo pipefail
log() { printf 'keel-setup: %s\n' "\$*"; }

for i in \$(seq 1 30); do
    curl --fail --silent --max-time 5 https://github.com >/dev/null 2>&1 && break
    sleep 2
done

export DEBIAN_FRONTEND=noninteractive
sudo apt-get update
sudo apt-get install --assume-yes --no-install-recommends \\
    zsh fish bat fzf zoxide just git-delta fd-find unattended-upgrades
sudo ln --symbolic --force /usr/bin/batcat /usr/local/bin/bat
sudo ln --symbolic --force /usr/bin/fdfind /usr/local/bin/fd
bat --version && fd --version

tmp="\$(mktemp --directory)"
cd "\$tmp"
fetch_tar() { # url, path-of-binary-inside, name
    curl --fail --silent --show-error --location --retry 5 --retry-delay 3 --retry-all-errors "\$1" -o a.tgz
    rm --recursive --force x && mkdir x && tar --extract --gzip --file a.tgz --directory x
    sudo install --mode=0755 "x/\$2" "/usr/local/bin/\$3"
    rm --force a.tgz
}
fetch_bin() { # url, name
    curl --fail --silent --show-error --location --retry 5 --retry-delay 3 --retry-all-errors "\$1" -o "\$tmp/\$2"
    sudo install --mode=0755 "\$tmp/\$2" "/usr/local/bin/\$2"
}

fetch_tar "https://github.com/starship/starship/releases/download/v${STARSHIP_VERSION}/starship-x86_64-unknown-linux-musl.tar.gz" \\
    "starship" starship
fetch_tar "https://github.com/atuinsh/atuin/releases/download/v${ATUIN_VERSION}/atuin-x86_64-unknown-linux-musl.tar.gz" \\
    "atuin-x86_64-unknown-linux-musl/atuin" atuin
fetch_tar "https://github.com/charmbracelet/gum/releases/download/v${GUM_VERSION}/gum_${GUM_VERSION}_Linux_x86_64.tar.gz" \\
    "gum_${GUM_VERSION}_Linux_x86_64/gum" gum
fetch_tar "https://github.com/jj-vcs/jj/releases/download/v${JJ_VERSION}/jj-v${JJ_VERSION}-x86_64-unknown-linux-musl.tar.gz" \\
    "jj" jj
fetch_bin "https://github.com/twpayne/chezmoi/releases/download/v${CHEZMOI_VERSION}/chezmoi-linux-amd64" chezmoi

cd / && rm --recursive --force "\$tmp"
starship --version; atuin --version; gum --version; jj --version; chezmoi --version

SCRIPT

embed gitconfig                /etc/gitconfig                    0644
embed keel-secret               /usr/local/bin/keel-secret        0755
embed keel-profile              /usr/local/bin/keel-profile       0755
embed keel-profile.service      /etc/systemd/system/keel-profile.service   0644

embed zz-keel-auto-upgrades /etc/apt/apt.conf.d/zz-keel-auto-upgrades 0644

cat <<'SCRIPT'
sudo systemctl daemon-reload
sudo systemctl enable --now keel-profile.service

# GIT_CONFIG_NOSYSTEM=1: bypass the /etc/gitconfig rewrite just installed and
# hit public github.com directly, so dotfiles bootstrap stays independent of
# the dev/prod tag (and therefore the gh-andreweick integration) -- matching
# today's behaviour, where dotfiles bake in at CI time regardless of tags.
GIT_CONFIG_NOSYSTEM=1 chezmoi init --apply --exclude=scripts,encrypted \
    https://github.com/andreweick/dotfiles.git
test -f "$HOME/.config/starship.toml"
test -f "$HOME/.zshrc"
test ! -e "$HOME/.config/age/key.txt"

printf '%s\n' '#!/bin/sh' \
    'exec chezmoi update --exclude=scripts,encrypted "$@"' \
    | sudo tee /usr/local/bin/keel-update-dotfiles >/dev/null
sudo chmod 0755 /usr/local/bin/keel-update-dotfiles

sudo chsh --shell /bin/zsh exedev

# Start only after setup's package/config work is complete.
sudo systemctl unmask apt-daily.service apt-daily-upgrade.service \
    apt-daily.timer apt-daily-upgrade.timer unattended-upgrades.service
sudo systemctl enable --now apt-daily.timer apt-daily-upgrade.timer unattended-upgrades.service

# No /etc/machine-id re-truncation: that landmine is specific to baking a
# package install into a SHARED Docker image layer. On a live VM, systemd
# already generated a unique id before this script ran, and apt-get on a
# running system does not touch an existing non-empty one.

# Completion marker for `just new-fast`'s wait loop -- unreached on failure.
touch "$HOME/.keel-setup-done"
log "done"
SCRIPT
